# Copyright (C) 2025 Miguel Salas Heras

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# File responsible for deploying the Docker container of the QoQo Quantum Cryptography simulation environment

services:
  qoqo-quantum-cryptography-docker:
    container_name: qoqo_quantum_cryptography_docker_container # container name
    stdin_open: true # for enabling terminal
    tty: true # for enabling terminal
    working_dir: /volume_docker_files/ # working directory
    build: # build image configuration
      context: . # location of the Dockerfile
      dockerfile: Dockerfile # dockerfile name
    image: qoqo-quantum-cryptography-docker-image # image name
    volumes:
      - ./volume_docker_files/:/volume_docker_files/ # mounting local directory to container
